"""dmind-handoff/v1 against the corpus generated by DayPilot's TypeScript reference."""

import hashlib
import json
from pathlib import Path

import pytest

from matrix_designer.dmind_handoff import build_handoff, check_changes, fnv1a, to_handoff_brief, valid_scope

DATA = json.loads((Path(__file__).parents[1] / "examples/dmind/handoff-cases.json").read_text(encoding="utf-8"))
PINNED = "d9390d6c404356763c8ee8150f176b9b8b4ff65737cc2d436ceb6fa5d2f2594a"


def test_corpus_matches_the_pin():
    text = json.dumps(DATA, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    assert hashlib.sha256(text.encode()).hexdigest() == PINNED


@pytest.mark.parametrize("text,expected", DATA["fnv"])
def test_fnv(text, expected):
    assert fnv1a(text) == expected


@pytest.mark.parametrize("path,expected", DATA["scopes"])
def test_scope_validity(path, expected):
    assert valid_scope(path) is expected


def test_handoff_and_brief_match_the_reference():
    h = build_handoff(DATA["diagram"])
    assert h == DATA["handoff"]
    assert to_handoff_brief(h) == DATA["brief"]


@pytest.mark.parametrize("case", DATA["checks"], ids=lambda c: c["name"])
def test_checks(case):
    assert check_changes(DATA["handoff"], case["files"], case["reviewed"]) == case["expect"]


def test_nothing_marked_is_refused_and_human_review_is_always_required():
    d = json.loads(json.dumps(DATA["diagram"]))
    for n in d["nodes"]:
        n.pop("metadata", None)
    with pytest.raises(ValueError):
        build_handoff(d)
    assert DATA["handoff"]["requiresHumanReview"] is True
    assert check_changes(DATA["handoff"], ["src/orders/validate.py"], False)["mayProceed"] is False


def test_hostile_text_cannot_break_out_of_the_brief_fences():
    brief = to_handoff_brief(DATA["handoff"])
    assert "`totals`" not in brief and "UNTRUSTED" in brief
