"""dmind-patch/v1 against the corpus shared with DayPilot (generated by its TypeScript reference)."""

import copy
import hashlib
import json
from pathlib import Path

import pytest

from matrix_designer.dmind_patch import PatchError, apply_patch, hash_diagram, parse_patch

CORPUS = Path(__file__).parents[1] / "examples/dmind/patch-cases.json"
DATA = json.loads(CORPUS.read_text(encoding="utf-8"))
# Canonical-JSON digest of the corpus; DayPilot pins the same value.
PINNED = "870b946b39bd8b2e414659196ac26211ae10ba8182d4b33d98f854ed63c3161a"


def test_corpus_matches_the_pin():
    text = json.dumps(DATA, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    assert hashlib.sha256(text.encode()).hexdigest() == PINNED


def test_hash_agrees_with_the_typescript_reference():
    assert hash_diagram(DATA["base"]) == DATA["base_hash"]


@pytest.mark.parametrize("case", DATA["cases"], ids=lambda c: c["name"])
def test_case(case):
    base = copy.deepcopy(DATA["base"])
    if case["expect"] == "ok":
        result = apply_patch(base, case["patch"])
        assert hash_diagram(result) == case["result_digest"]
    else:
        with pytest.raises(PatchError) as info:
            apply_patch(base, case["patch"])
        assert info.value.reason == case["expect"]
    assert base == DATA["base"], "input must never be modified"


def test_pollution_and_shape_are_refused():
    good = DATA["cases"][0]["patch"]
    for bad in (None, [], {**good, "extra": 1}, {**good, "origin": "admin"}, {**good, "ops": []}):
        with pytest.raises(PatchError):
            parse_patch(bad)
    pol = json.loads('{"op":"update_node","id":"n1","set":{"__proto__":{"x":1}}}')
    with pytest.raises(PatchError):
        parse_patch({**good, "ops": [pol]})
